apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
  namespace: podinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:5.0.0
          ports:
            - containerPort: 9898
